spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

backbase:
  event-emitter:
    #comma-separated list topic names
    topic-names: Backbase.communication.push-low-priority,Backbase.communication.push-medium-priority,Backbase.communication.push-medium-priority,Backbase.communication.notifications-low-priority,Backbase.communication.notifications-medium-priority,Backbase.communication.notifications-high-priority,Backbase.communication.message-center-low-priority,Backbase.communication.message-center-medium-priority,Backbase.communication.message-center-high-priority,Backbase.communication.sms-low-priority,Backbase.communication.sms-medium-priority,Backbase.communication.sms-high-priority,Backbase.communication.email-low-priority,Backbase.communication.email-medium-priority,Backbase.communication.email-high-priority

logging:
  level:
    com:
      backbase: DEBUG
    org:
      springframework:
        cloud: DEBUG
