server:
  port: 8080

spring:
  application:
    name: event-emitter
  cloud:
    stream:
      default-binder: activemq
  liquibase:
    enabled: false

backbase:
  security:
    public:
      paths:
        - /events/*
        - /mass-emit/*

eureka:
  instance:
    appname: ${spring.application.name}
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadataMap:
      public: true

logging:
  level:
    com:
      netflix:
        discovery: OFF

# The below config is an example of how to enable SCS bindings actuator endpoint which is disabled by default on SSDK
management:
  endpoint:
    bindings:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - bindings
          - health