server:
  port: 8079
spring:
  application:
    name: event-emitter
  cloud:
    stream:
#      default-binder: activemq
      default-binder: kafka
  kafka:
    bootstrap-servers: ${kafka.host:UAIEV8759NBM.LEVI9.COM}:29092
  liquibase:
    enabled: false
backbase:
  security:
    public:
      paths: /events/*
logging:
  level:
    com:
      netflix:
        discovery: OFF

# The below config is an example of how to enable SCS bindings actuator endpoint which is disabled by default on SSDK
management:
  endpoint:
    bindings:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - bindings
          - health