server:
  port: 8080

backbase:
  event-emitter:
    topic-names: ""
  security:
    public:
      paths:
        - /events
        - /events/*
        - /mass-emit/*

spring:
  application:
    name: event-emitter
  cloud:
    stream:
      default-binder: activemq
      bindings:
        consumeEvent-in-0:
          destination: ${backbase.event-emitter.topic-names}
  liquibase:
    enabled: false

eureka:
  instance:
    appname: ${spring.application.name}
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    metadataMap:
      public: true

logging:
  level:
    com:
      netflix:
        discovery: OFF
      backbase: WARN
    org:
      springframework:
        cloud: WARN

# The below config is an example of how to enable SCS bindings actuator endpoint which is disabled by default on SSDK
management:
  endpoint:
    bindings:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - bindings
          - health