name: Maven Verify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    name: Maven Verify
    uses: backbase/workflows/.github/workflows/maven-verify.yml@main
    with:
      java-version: "21"
    secrets:
      maven-username: ${{ secrets.REPO_USERNAME }}
      maven-password: ${{ secrets.REPO_PASSWORD }}